#!/bin/bash

# Install basic tools to get started
  sudo pacman -Syu base-devel zsh make git curl vim xorg arandr 
# Creates a home dir if one is not there

  if ! [ -d $HOME ]
  then
    mkdir -p /Home/$USER
  fi

# checks for the existence of a source folder in the users home dir

  if ! [-d $HOME/Src ]
  then
    mkdir -p $HOME/Src
  fi
  cd $HOME/Src

# Install Oh-My-Zsh for zsh themes
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Clones the package-query dependency for yaourt then builds it if not already installed
  if ! [ -d $HOME/Src/package-query ]
  then {
    git clone https://aur.archlinux.org/package-query.git
    cd $HOME/Src/package-query
    makepkg -si
    cd ..
    }
  fi

# Clones yaourt and builds it if not already installed
  if ! [ -d $HOME/Src/yaourt ]
  then {
    git clone https://aur.archlinux.org/yaourt.git
    cd yaourt
    makepkg -si
    }
  fi

# Updates systems with AUR packages and DE tools
  yaourt -Syuab i3-gaps-git conky compton xautolock i3bar lightdm lightdm-webkit2-greeter chronie \
	  ranger alsa-firmware alsa-lib ffmpeg w3m vlc libreoffice-fresh gnome-disk-utility \
	  testdisk parted ntfs-3g hfsprogs samba kerebos rust cargo-git g++ clamtk mutt \
	  htop refind-efi

# Download and install Pathogen for Vim plugins
  mkdir -p ~/.vim/autoload ~/.vim/bundle 
  sh -c "$(curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim)"

# Creates the .vim dir and clones plugins from github
  if ! [ -d $HOME/.vim ]
  then 
    mkdir $HOME/.vim
  fi

  vimPath=$HOME/.vim/bundle/

  git clone https://github.com/scrooloose/nerdtree.git $vimPath # nerdTree

  git clone https://github.com/vim-syntastic/syntastic.git $vimPath # syntastic

  git clone https://github.com/vim-airline/vim-airline.git $vimPath # vim-airline

  git clone https://github.com/airblade/vim-gitgutter.git $vimPath # vim-gitgutter

  git clone https://github.com/ervandew/supertab.git $vimPath # supertab

# Add services to systemd
  systemctl enable lightdm xautolock

# Set user settings
  chsh -s /bin/zsh
  echo "Shell has been changed to ZSH"

# Move personal config files to $Home
  cd $HOME/Src/Personal_Configs
  cp -rfvL .zshrc .config .vimrc .conkyrc .bashrc $HOME/
  echo "Config files have been copied to $HOME"

