#!/usr/bin/bash

# Handle XRandR randomized monitor names
MONITOR=$(polybar -m | tail -1 | sed -e "s/:.*$//g")

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar
polybar -c "${HOME}/.config/polybar/config" top &
